language: java
sudo: required
addons:
  sonarcloud:
    organization: "elysantos"
    token:
      secure: SONAR_TOKEN
cache:
  directories:
    - '$HOME/.sonar/cache'
script:
  - sonar-scanner

notifications:
  email: false