spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:**/mappers/*Mapper.xml
  type-aliases-package: jar.model
  type-handlers-package: jar.mapper.typehandler

---
# Coloque aqui suas configurações de Desenvolvimento
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    platform: org.hibernate.dialect.H2Dialect
    driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: dev
server:
  port: 9898
